<?php

define( 'PAWFRIENDS_CORE_VERSION', '1.0' );
define( 'PAWFRIENDS_CORE_ABS_PATH', dirname( __FILE__ ) );
define( 'PAWFRIENDS_CORE_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'PAWFRIENDS_CORE_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'PAWFRIENDS_CORE_ASSETS_PATH', PAWFRIENDS_CORE_ABS_PATH . '/assets' );
define( 'PAWFRIENDS_CORE_ASSETS_URL_PATH', PAWFRIENDS_CORE_URL_PATH . 'assets' );
define( 'PAWFRIENDS_CORE_CPT_PATH', PAWFRIENDS_CORE_ABS_PATH . '/post-types' );
define( 'PAWFRIENDS_CORE_CPT_URL_PATH', PAWFRIENDS_CORE_URL_PATH . 'post-types' );
define( 'PAWFRIENDS_CORE_SHORTCODES_PATH', PAWFRIENDS_CORE_ABS_PATH . '/shortcodes' );
define( 'PAWFRIENDS_CORE_SHORTCODES_URL_PATH', PAWFRIENDS_CORE_URL_PATH . 'shortcodes' );